"use client";

import { useCallback, useEffect, useState } from "react";
import { FileText, ShieldCheck } from "lucide-react";
import { AdminCard, AdminEmpty, AdminPage, AdminPageIntro, AdminRefreshButton } from "./AdminUi";

type Entry = { id:number; adminUserId:number; adminName:string; action:string; entityType:string; entityId:number|null; result:string; metadata:string|null; createdAt:string };
function fmt(value:string){ return value ? new Date(value.replace(" ","T")+"Z").toLocaleString("fa-IR") : "—"; }

export default function AdminAuditClient({ initial }: { initial?: Entry[] }){
 const [items,setItems]=useState<Entry[]>(initial ?? []),[loading,setLoading]=useState(!initial),[error,setError]=useState(""),[result,setResult]=useState("");
 const refresh=useCallback(async()=>{setLoading(true);setError("");try{const q=result?`?result=${encodeURIComponent(result)}`:"";const r=await fetch(`/api/admin/audit${q}`,{cache:"no-store"});const body=await r.json();if(!r.ok)throw new Error(body?.error||"خطا در دریافت گزارش رویدادها");setItems(Array.isArray(body)?body:[])}catch(e){setError(e instanceof Error?e.message:"خطا در دریافت گزارش رویدادها")}finally{setLoading(false)}},[result]);
 useEffect(()=>{if(!initial)void refresh()},[initial,refresh]);
 return <AdminPage className="max-w-none">
  <AdminPageIntro eyebrow="فاز ۵ · حسابرسی" title="گزارش حسابرسی" description="عملیات حساس پنل و Engine با نتیجه و شناسه مدیر ثبت می‌شوند." action={<AdminRefreshButton onClick={()=>void refresh()} loading={loading}/>}/>
  <div className="mb-4 flex flex-wrap gap-2"><button type="button" onClick={()=>setResult("")} className={`inline-flex min-h-10 items-center justify-center gap-2 rounded-[5px] px-3 text-xs font-black transition disabled:pointer-events-none disabled:opacity-50 ${!result?"bg-brand-blue text-white hover:brightness-110":"border border-brand-surface_hover bg-brand-surface_hover/60 text-white hover:bg-brand-surface_hover"}`}>همه</button><button type="button" onClick={()=>setResult("success")} className={`inline-flex min-h-10 items-center justify-center gap-2 rounded-[5px] px-3 text-xs font-black transition disabled:pointer-events-none disabled:opacity-50 ${result==="success"?"bg-brand-blue text-white hover:brightness-110":"border border-brand-surface_hover bg-brand-surface_hover/60 text-white hover:bg-brand-surface_hover"}`}>موفق</button><button type="button" onClick={()=>setResult("failed")} className={`inline-flex min-h-10 items-center justify-center gap-2 rounded-[5px] px-3 text-xs font-black transition disabled:pointer-events-none disabled:opacity-50 ${result==="failed"?"bg-brand-blue text-white hover:brightness-110":"border border-brand-surface_hover bg-brand-surface_hover/60 text-white hover:bg-brand-surface_hover"}`}>ناموفق</button></div>
  {error&&<div className="mb-4 rounded-[5px] border border-red-400/20 bg-red-500/5 p-4 text-xs text-red-200">{error}</div>}
  <AdminCard className="overflow-hidden"><div className="flex items-center gap-3 border-b border-white/[.06] p-5"><span className="flex h-9 w-9 items-center justify-center rounded-[5px] bg-brand-blue/10 text-brand-blue"><FileText size={17}/></span><div><h2 className="text-sm font-black text-white">آخرین عملیات</h2><p className="mt-1 text-[10px] text-brand-m_khonsa">جدیدترین ۱۰۰ رویداد</p></div></div>{loading&&!items.length?<AdminEmpty title="در حال دریافت لاگ‌ها..."/>:!items.length?<AdminEmpty title="لاگی پیدا نشد."/>:<div className="overflow-x-auto"><table className="w-full text-right text-xs"><thead><tr className="border-b border-white/[.06] text-brand-m_khonsa"><th className="px-5 py-3">زمان</th><th>مدیر</th><th>عملیات</th><th>Entity</th><th>نتیجه</th><th className="px-5">Metadata</th></tr></thead><tbody>{items.map(i=><tr key={i.id} className="border-b border-white/[.04] align-top"><td className="px-5 py-3 whitespace-nowrap text-brand-m_khonsa" dir="ltr">{fmt(i.createdAt)}</td><td className="py-3"><div className="font-bold text-white">{i.adminName||`User #${i.adminUserId}`}</div><div className="text-[10px] text-brand-m_khonsa">ID {i.adminUserId}</div></td><td className="py-3 font-mono text-[11px] text-white" dir="ltr">{i.action}</td><td className="py-3 text-brand-m_khonsa">{i.entityType||"—"}{i.entityId?` #${i.entityId}`:""}</td><td className="py-3">{i.result==="success"?<span className="inline-flex items-center gap-1 text-emerald-300"><ShieldCheck size={13}/> موفق</span>:<span className="text-red-300">ناموفق</span>}</td><td className="px-5 py-3 max-w-[360px]"><pre className="whitespace-pre-wrap break-words text-[10px] text-brand-m_khonsa" dir="ltr">{i.metadata||"—"}</pre></td></tr>)}</tbody></table></div>}</AdminCard>
 </AdminPage>
}
