"use client";

import Link from "next/link";
import { useEffect, useState, type ReactNode } from "react";
import { ArrowRight, MessageSquare, StickyNote, UserCheck, Users } from "lucide-react";
import { useAdminContext } from "./AdminContext";
import { AdminBadge, AdminButton, AdminCard, AdminEmpty, AdminField, AdminFieldRow, AdminPage, AdminPageIntro, AdminSectionHeader, AdminSelect, AdminTextarea } from "./AdminUi";

const TICKET_STATUS_LABELS: Record<string,string> = { open:"باز", claimed:"در اختیار ادمین", waiting_user:"در انتظار کاربر", waiting_staff:"در انتظار پشتیبانی", resolved:"حل‌شده", closed:"بسته‌شده" };
const TICKET_PRIORITY_LABELS: Record<string,string> = { low:"کم", normal:"عادی", high:"زیاد", urgent:"فوری" };
type Detail={ticket:{databaseId:number;title:string;date:string;status:string;priority:string;customerId:number|null;customerName:string;customerEmail:string;linkedOrderId:number|null;assigneeId:number|null;assigneeName:string|null;claimExpiresAt:string|null};replies:Array<any>;events:Array<any>;internalNotes:Array<any>};

export default function AdminTicketDetail({data:initialData,id}:{data?:Detail;id:number}){
  const {permissions}=useAdminContext();
  const [data,setData]=useState<Detail|null>(initialData ?? null),[reply,setReply]=useState(""),[note,setNote]=useState(""),[loading,setLoading]=useState(!initialData),[actionLoading,setActionLoading]=useState(false),[status,setStatus]=useState(initialData?.ticket.status ?? "open"),[staff,setStaff]=useState<Array<{databaseId:number;name:string;email:string}>>([]),[assignee,setAssignee]=useState(initialData?.ticket.assigneeId?String(initialData.ticket.assigneeId):""),[error,setError]=useState("");
  useEffect(()=>{if(initialData)return;fetch(`/api/admin/tickets/${id}`,{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d?.error||"تیکت یافت نشد");setData(d);setStatus(d.ticket.status);setAssignee(d.ticket.assigneeId?String(d.ticket.assigneeId):"")}).catch(e=>setError(e instanceof Error?e.message:"خطا در دریافت تیکت")).finally(()=>setLoading(false));},[id,initialData]);
  useEffect(()=>{if(!permissions.includes("tickets.write"))return;fetch("/api/admin/tickets?staff=1",{cache:"no-store"}).then(r=>r.ok?r.json():null).then(d=>setStaff(d?.staff||[])).catch(()=>{});},[permissions]);
  const post=async(body:any)=>{const r=await fetch("/api/admin/tickets",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok)throw new Error();return r.json()};
  const reload=async()=>{if(!data)return;const r=await fetch(`/api/admin/tickets/${data.ticket.databaseId}`,{cache:"no-store"});if(!r.ok)return;const d=await r.json();setData(d);setStatus(d.ticket.status);setAssignee(d.ticket.assigneeId?String(d.ticket.assigneeId):"")};
  const act=async(body:any)=>{setActionLoading(true);try{await post(body);await reload()}finally{setActionLoading(false)}};

  if(!data) return <AdminPage><Link href="/admin/tickets" className="inline-flex items-center gap-2 text-xs font-bold text-brand-m_khonsa hover:text-white"><ArrowRight size={15}/> بازگشت به تیکت‌ها</Link>{error&&<div className="mt-4 rounded-[4px] border border-red-500/20 bg-red-500/5 p-4 text-xs text-red-200">{error}</div>}<div className="mt-4"><AdminEmpty title={loading?"تیکت در حال دریافت اطلاعات...":"تیکت پیدا نشد."}/></div></AdminPage>;

  const statusTone=data.ticket.status==="resolved"||data.ticket.status==="closed"?"success":data.ticket.status==="open"?"warning":"info" as "success"|"warning"|"info";
  return <AdminPage>
    <div className="mb-4 flex items-center justify-between gap-3"><Link href="/admin/tickets" className="inline-flex items-center gap-2 text-xs font-bold text-brand-m_khonsa hover:text-white"><ArrowRight size={15}/> بازگشت به تیکت‌ها</Link><AdminBadge tone={statusTone}>{TICKET_STATUS_LABELS[data.ticket.status]??data.ticket.status}</AdminBadge></div>
    <AdminPageIntro eyebrow="پرونده تیکت" title={data.ticket.title} description={`#${data.ticket.databaseId} · اولویت ${TICKET_PRIORITY_LABELS[data.ticket.priority]??data.ticket.priority}`} action={permissions.includes("tickets.claim")?<AdminButton variant="primary" onClick={()=>act({action:"claim",ticketId:data.ticket.databaseId})} disabled={actionLoading}><UserCheck size={14}/> دریافت مسئولیت</AdminButton>:undefined}/>
    {error&&<div className="mb-4 rounded-[4px] border border-red-500/20 bg-red-500/5 p-4 text-xs text-red-200">{error}</div>}
    <div className="grid grid-cols-1 gap-4 xl:grid-cols-[1.35fr_0.75fr]">
      <div className="space-y-4">
        <AdminCard className="overflow-hidden"><AdminSectionHeader icon={<MessageSquare size={17}/>} title="گفتگو" description="پیام‌های مشتری و پاسخ‌های تیم"/><div className="max-h-[520px] space-y-2 overflow-y-auto p-4">{data.replies.map((r:any)=><div key={r.id} className={`rounded-[4px] border border-brand-surface_hover p-3 ${r.authorRole==="staff"?"bg-brand-blue/5":"bg-brand-bg/40"}`}><div className="flex justify-between gap-3"><div className="text-xs font-black text-white">{r.authorName}</div><div className="text-[10px] text-brand-m_khonsa">{r.createdAt?new Date(r.createdAt).toLocaleString("fa-IR"):"—"}</div></div><div className="mt-2 whitespace-pre-wrap text-xs leading-6 text-white">{r.content}</div></div>)}{data.replies.length===0&&<AdminEmpty title="گفتگویی ثبت نشده است."/>}</div>{permissions.includes("tickets.write")&&<div className="border-t border-white/[.06] p-4"><AdminTextarea value={reply} onChange={e=>setReply(e.target.value)} rows={4} placeholder="پاسخ به مشتری..."/><div className="mt-2 flex justify-end"><AdminButton variant="primary" onClick={async()=>{await act({action:"reply",ticketId:data.ticket.databaseId,content:reply});setReply("")}} disabled={actionLoading||!reply.trim()}>ارسال پاسخ</AdminButton></div></div>}</AdminCard>
        <AdminCard className="overflow-hidden"><AdminSectionHeader icon={<StickyNote size={17}/>} title="یادداشت‌های داخلی"/><div className="space-y-2 p-4">{data.internalNotes.map((n:any)=><div key={n.id} className="rounded-[4px] border border-brand-surface_hover bg-brand-bg/30 p-3"><div className="whitespace-pre-wrap text-xs leading-6 text-white">{n.content}</div><div className="mt-2 text-[10px] text-brand-m_khonsa">{n.adminName} · {n.createdAt?new Date(n.createdAt).toLocaleString("fa-IR"):"—"}</div></div>)}{data.internalNotes.length===0&&<AdminEmpty title="یادداشت داخلی وجود ندارد."/>}</div>{permissions.includes("tickets.write")&&<div className="border-t border-white/[.06] p-4"><AdminTextarea value={note} onChange={e=>setNote(e.target.value)} rows={3} placeholder="یادداشت داخلی..."/><div className="mt-2 flex justify-end"><AdminButton onClick={async()=>{await act({action:"note",ticketId:data.ticket.databaseId,content:note});setNote("")}} disabled={actionLoading||!note.trim()}>ثبت یادداشت</AdminButton></div></div>}</AdminCard>
      </div>
      <div className="space-y-4">
        <AdminCard className="overflow-hidden"><AdminSectionHeader title="گردش تیکت"/><div className="space-y-3 p-4">{permissions.includes("tickets.write")?<><AdminSelect value={status} onChange={e=>setStatus(e.target.value)}>{[["open","باز"],["claimed","در اختیار ادمین"],["waiting_user","در انتظار کاربر"],["waiting_staff","در انتظار پشتیبانی"],["resolved","حل‌شده"],["closed","بسته‌شده"]].map(([value,label])=><option key={value} value={value}>{label}</option>)}</AdminSelect><AdminButton variant="primary" className="w-full" onClick={()=>act({action:"status",ticketId:data.ticket.databaseId,status})} disabled={actionLoading||status===data.ticket.status}>ذخیره وضعیت</AdminButton></>:<AdminFieldRow label="وضعیت" value={TICKET_STATUS_LABELS[data.ticket.status]??data.ticket.status} ltr={false}/>}</div></AdminCard>
        <AdminCard className="overflow-hidden"><AdminSectionHeader icon={<Users size={17}/>} title="مسئول تیکت"/><div className="p-4">{permissions.includes("tickets.write")?<><AdminSelect value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">انتخاب مدیر</option>{staff.map(s=><option key={s.databaseId} value={s.databaseId}>{s.name} · {s.email}</option>)}</AdminSelect><AdminButton className="mt-2 w-full" onClick={()=>assignee&&act({action:"reassign",ticketId:data.ticket.databaseId,adminUserId:Number(assignee)})} disabled={actionLoading||!assignee}>تغییر مسئول</AdminButton></>:<AdminFieldRow label="مسئول" value={data.ticket.assigneeName||"بدون مسئول"} ltr={false}/>}</div></AdminCard>
        <AdminCard className="overflow-hidden"><AdminSectionHeader title="اطلاعات مشتری"/><div className="p-4"><AdminFieldRow label="نام" value={data.ticket.customerName||"—"} ltr={false}/><AdminFieldRow label="ایمیل" value={data.ticket.customerEmail||"—"}/>{data.ticket.linkedOrderId&&<Link href={`/admin/orders/${data.ticket.linkedOrderId}`} className="mt-2 block text-xs font-bold text-brand-blue hover:text-white">سفارش مرتبط #{data.ticket.linkedOrderId}</Link>}</div></AdminCard>
        <AdminCard className="overflow-hidden"><AdminSectionHeader title="تاریخچه"/><div className="space-y-2 p-4">{data.events.map((e:any)=><div key={e.id} className="border-b border-brand-surface_hover pb-2 last:border-0"><div className="text-[10px] text-brand-m_khonsa">{e.adminName} · {e.createdAt?new Date(e.createdAt).toLocaleString("fa-IR"):"—"}</div><div className="mt-1 text-xs text-white">{e.type} {e.fromStatus&&`· ${TICKET_STATUS_LABELS[e.fromStatus] ?? e.fromStatus} ← ${TICKET_STATUS_LABELS[e.toStatus] ?? e.toStatus}`}</div></div>)}</div></AdminCard>
      </div>
    </div>
  </AdminPage>;
}
