import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header/Header";
import { CartProvider } from "@/constants/CartContext";

const yekanFont = localFont({
  src: "./fonts/Yekan.woff",
  variable: "--font-yekan",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${yekanFont.variable} font-sans antialiased`}>
        {/* رپ کردن کل برنامه با کانتکست سبد خرید */}
        <CartProvider>
          <Header /> 
          {children}
        </CartProvider>
      </body>
    </html>
  );
}